package de.kapschefsky.android.aviv.test.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val DarkColorScheme =
    darkColorScheme(
        primary = Color(0xffaac7ff),
        secondary = Color(0xffb9c7e5),
        tertiary = Color(0xffabcbdb),
        error = Color(0xffffb4ab),
        onPrimary = Color(0xff002f64),
        onSecondary = Color(0xff233148),
        onTertiary = Color(0xff123441),
        onError = Color(0xff690005),
        errorContainer = Color(0xff93000a),
        onErrorContainer = Color(0xffffdad6),
        primaryContainer = Color(0xff769cdf),
        onPrimaryContainer = Color(0xff00326a),
        secondaryContainer = Color(0xff3c4962),
        onSecondaryContainer = Color(0xffabb9d6),
        tertiaryContainer = Color(0xff7595a4),
        onTertiaryContainer = Color(0xff092d3a),
        surfaceDim = Color(0xff121317),
        surface = Color(0xff121317),
        surfaceBright = Color(0xff38393e),
        surfaceContainerLowest = Color(0xff0c0e12),
        surfaceContainerLow = Color(0xff1a1c20),
        surfaceContainer = Color(0xff1e2024),
        surfaceContainerHigh = Color(0xff282a2e),
        surfaceContainerHighest = Color(0xff333539),
        onSurface = Color(0xffe2e2e8),
        onSurfaceVariant = Color(0xffc3c6d2),
        outline = Color(0xff8d909b),
        outlineVariant = Color(0xff434750),
        inverseSurface = Color(0xffe2e2e8),
        inverseOnSurface = Color(0xff2f3035),
        inversePrimary = Color(0xff365e9d),
        scrim = Color(0xff000000),
    )

internal val LightColorScheme =
    lightColorScheme(
        primary = Color(0xff365e9d),
        secondary = Color(0xff515f79),
        tertiary = Color(0xff41606e),
        error = Color(0xffba1a1a),
        onPrimary = Color(0xffffffff),
        onSecondary = Color(0xffffffff),
        onTertiary = Color(0xffffffff),
        onError = Color(0xffffffff),
        errorContainer = Color(0xffffdad6),
        onErrorContainer = Color(0xff93000a),
        primaryContainer = Color(0xff769cdf),
        onPrimaryContainer = Color(0xff00326a),
        secondaryContainer = Color(0xffd2e0ff),
        onSecondaryContainer = Color(0xff55637d),
        tertiaryContainer = Color(0xff597987),
        onTertiaryContainer = Color(0xfffbfdff),
        surfaceDim = Color(0xffdad9df),
        surface = Color(0xfff9f9ff),
        surfaceBright = Color(0xfff9f9ff),
        surfaceContainerLowest = Color(0xffffffff),
        surfaceContainerLow = Color(0xfff3f3f9),
        surfaceContainer = Color(0xffeeedf3),
        surfaceContainerHigh = Color(0xffe8e7ed),
        surfaceContainerHighest = Color(0xffe2e2e8),
        onSurface = Color(0xff1a1c20),
        onSurfaceVariant = Color(0xff434750),
        outline = Color(0xff737781),
        outlineVariant = Color(0xffc3c6d2),
        inverseSurface = Color(0xff2f3035),
        inverseOnSurface = Color(0xfff1f0f6),
        inversePrimary = Color(0xffaac7ff),
        scrim = Color(0xff000000),
    )